#!/usr/bin/env bash
#Installs and configures HAproxy in a load balancer server

sudo apt-get -y update
sudo apt-get -y install software-properties-common
sudo add-apt-repository -y ppa:vbernat/haproxy-2.0
sudo apt-get -y install haproxy

echo "ENABLED=1" | sudo tee -a /etc/default/haproxy

{
echo -e "\

frontend web_frontend
\tbind *:80
\tmode http
\tdefault_backend web_backend

backend web_backend
\tbalance roundrobin
\tserver 24321-web-01 54.146.93.216:80 check
\tserver 24321-web-02 35.174.204.198:80 check"
} | sudo tee -a /etc/haproxy/haproxy.cfg

sudo service haproxy restart
