#!/usr/bin/env bash
#Installs and configures HAproxy in a load balancer server

apt-get install -y software-properties-common
add-apt-repository -y ppa:vbernat/haproxy-2.0
apt-get update
apt-get install -y haproxy

echo "ENABLED=1" >> /etc/default/haproxy
mv /etc/haproxy/haproxy.cfg{,.original}
touch /etc/haproxy/haproxy.cfg
    
printf %s "
frontend web_frontend
	bind *:80
	mode http
	default_backend web_backend

backend web_backend
	balance roundrobin
	server 24321-web-01 54.146.93.216:80 check
	server 24321-web-02 35.174.204.198:80 check"
" >> /etc/haproxy/haproxy.cfg

service haproxy start
